const translations = {
  pt: {},
  es: {
    skip: "Ir al contenido",
    brandRole: "Perfil deportivo",
    menu: "Abrir menú",
    navProfile: "Perfil",
    navVideos: "Vídeos",
    navJourney: "Trayectoria",
    navContact: "Contacto",
    heroEyebrow: "Atleta brasileño • Sub-15",
    heroPosition: "Defensa central zurdo <i>•</i> Lateral izquierdo",
    heroRoute: "Brasil <span>↗</span> España",
    watchHighlights: "Ver mejores momentos",
    viewProfile: "Ver perfil del atleta",
    institutionalContact: "Contacto institucional",
    downloadCv: "Descargar currículum deportivo",
    photoFallback: "Atleta de fútbol",
    photoLabel: "Defensa central • Lateral izquierdo",
    profileKicker: "01 — Datos del atleta",
    profileTitle: "Información objetiva",
    category: "Categoría",
    mainPosition: "Posición principal",
    secondaryPosition: "Posición complementaria",
    centerBack: "Defensa central",
    leftBack: "Lateral izquierdo",
    dominantFoot: "Pie dominante",
    leftFoot: "Izquierdo",
    nationality: "Nacionalidad",
    brazilian: "Brasileña",
    base: "Base",
    baseValue: "São Paulo, Brasil",
    experience: "Experiencia",
    experienceValue: "Brasil y España",
    languages: "Idiomas",
    languagesValue: "Portugués, Inglés y Español",
    highlightsKicker: "02 — Mejores momentos",
    highlightsTitle: "Vídeos para análisis",
    highlightsIntro: "Registros disponibles para observar al atleta en el campo.",
    mainVideo: "Vídeo principal",
    videoTwo: "Vídeo 02",
    videoThree: "Vídeo 03",
    highlightsName: "Mejores momentos — Thiago Cicala",
    openYoutube: "Abrir en YouTube ↗",
    finalVideoLabel: "Final",
    finalVideoTitle: "Gol decisivo de la final — Thiago Cicala",
    finalIframeTitle: "Gol decisivo de Thiago Cicala en la final del Campeonato Municipal de Louveira",
    semifinalVideoLabel: "Semifinal",
    semifinalVideoTitle: "Gol de la semifinal — Thiago Cicala",
    semifinalIframeTitle: "Gol de Thiago Cicala en la semifinal del Campeonato Municipal de Louveira",
    semifinalKicker: "Guarani — Campeonato Municipal de Louveira",
    semifinalTitle: "Participación directa en la remontada",
    semifinalDescription: "Thiago dio la asistencia para el gol del empate y marcó el gol de la remontada, contribuyendo a la clasificación de Guarani para la final.",
    semifinalStatsLabel: "Indicadores de la semifinal",
    semifinalAssist: "asistencia",
    semifinalGoal: "gol",
    semifinalQualification: "Clasificación para la final",
    semifinalAltDuel: "Thiago Cicala disputando el balón en la semifinal del Campeonato Municipal de Louveira",
    semifinalAltBall: "Thiago Cicala con el balón durante la semifinal con Guarani",
    semifinalAltPortrait: "Retrato de Thiago Cicala en el campo con la camiseta de Guarani",
    semifinalAltTeam: "Thiago Cicala con compañeros de Guarani después de clasificarse para la final",
    semifinalCaptionDuel: "Disputa de balón en la semifinal",
    semifinalCaptionBall: "Thiago con el balón",
    semifinalCaptionPortrait: "Concentración en el campo",
    semifinalCaptionTeam: "Después de clasificarse para la final",
    semifinalVideoActionsLabel: "Vídeo de la semifinal",
    watchSemifinalGoal: "Ver el gol de la semifinal",
    openSemifinalYoutube: "Abrir en YouTube ↗",
    finalKicker: "Final — Campeonato Municipal de Louveira",
    finalTitle: "Gol decisivo en el último minuto",
    finalDescription: "En la final del Campeonato Municipal de Louveira, Thiago marcó en el último minuto el gol de la victoria que confirmó el título de Guarani.",
    finalStatsLabel: "Momentos destacados de la final",
    finalWinningGoal: "Gol de la victoria",
    finalLastMinute: "Último minuto",
    finalChampion: "Título conquistado",
    finalCelebration: "Celebración del gol decisivo",
    finalPitch: "Concentración en la final",
    finalShirt: "Guarani • Camiseta 7",
    finalLineup: "Equipo antes de la final",
    finalTrophy: "Registro después del título",
    finalTeammates: "Compañeros y trofeo",
    finalChampions: "Guarani campeón",
    finalAltCelebration: "Thiago Cicala celebrando el gol decisivo de la victoria en el último minuto de la final",
    finalAltPitch: "Thiago Cicala en el campo durante la final con Guarani",
    finalAltShirt: "Thiago Cicala en el campo con la camiseta número 7 de Guarani",
    finalAltLineup: "Equipo de Guarani reunido en el campo antes de la final",
    finalAltTrophy: "Thiago Cicala sosteniendo el trofeo después del título con Guarani",
    finalAltTeammates: "Thiago Cicala con compañeros de Guarani y el trofeo del campeonato",
    finalAltChampions: "Equipo de Guarani reunido con el trofeo después de conquistar el campeonato",
    finalVideoActionsLabel: "Vídeo de la final",
    watchFinalGoal: "Ver el gol de la final",
    openFinalYoutube: "Abrir en YouTube ↗",
    qualitiesKicker: "03 — Características",
    qualitiesTitle: "Perfil en el campo",
    technical: "Técnicas",
    technicalText: "Pase corto, envíos largos, conducción y construcción desde la defensa.",
    tactical: "Tácticas",
    tacticalText: "Lectura de juego, posicionamiento, cobertura y apoyo a la salida de balón.",
    physical: "Físicas",
    physicalText: "Salto, velocidad, presencia en los duelos y capacidad de recuperación.",
    developing: "En desarrollo",
    developingText: "Finalización, repertorio ofensivo y desarrollo técnico continuo.",
    preparationKicker: "Preparación multidisciplinaria",
    preparationTitle: "Desarrollo físico orientado al fútbol",
    preparationIntro: "Una estructura complementaria que reúne atletismo y entrenamiento individualizado para ampliar la formación física y deportiva de Thiago.",
    athleticsTitle: "Atletismo aplicado",
    athleticsText: "Desde hace cuatro meses, Thiago realiza un trabajo complementario de atletismo en la CBAt bajo la orientación del profesor Marcelo, profesional con medallas de oro conquistadas en competiciones de la modalidad.",
    footballPersonalTitle: "Entrenamiento individualizado",
    footballPersonalText: "Trabajo personalizado con el profesor Paulo Capucho, orientado a las demandas físicas y deportivas específicas del fútbol.",
    appliedExperienceTitle: "Experiencia de alto rendimiento",
    appliedExperienceText: "Thiago también trabaja con el profesor Robinho, exatleta formado en las categorías inferiores del Santos, que llegó al primer equipo de Bragantino siendo muy joven, jugó en Bélgica y actualmente se dedica a la formación de atletas.",
    journeyKicker: "04 — Trayectoria",
    journeyTitle: "Formación deportiva",
    journeyIntro: "Experiencias de entrenamiento, formación, torneo y observación en Brasil y España.",
    timelineStart: "Inicio de la formación",
    timelineStartText: "Primeros años de entrenamiento y construcción de fundamentos.",
    timelineFirstTeam: "Primer equipo",
    timelineFirstTeamText: "Entrada en el fútbol organizado en el estado de São Paulo.",
    timelineMethod: "Experiencia de formación",
    timelineMethodText: "Contacto con una metodología de entrenamiento vinculada a la academia de Barcelona.",
    timelineMicText: "Participación en una competición internacional en Cataluña con BCN Academy.",
    timelineMislataText: "Periodo de entrenamientos y observación en Valencia, España.",
    current: "Actual",
    timelineBrazil: "Formación en Brasil",
    timelineBrazilText: "Desarrollo técnico, físico y competitivo en Brasil.",
    next: "Próximo",
    timelineGoal: "Objetivo profesional",
    timelineGoalText: "Continuar la formación en un entorno competitivo, conciliando fútbol y educación.",
    internationalKicker: "05 — Experiencia internacional",
    internationalTitle: "Experiencias en España",
    internationalText: "Experiencias de formación en Barcelona, competición en Cataluña y periodo de entrenamientos y observación en Valencia.",
    catalonia: "Cataluña",
    valencia: "Valencia",
    marcetKicker: "Marcet — registro en el campo",
    marcetTitle: "Experiencia de formación",
    marcetIntro: "Imágenes autorizadas de la participación de Thiago en actividades deportivas con Marcet.",
    marcetAction: "Disputa de balón",
    marcetMatch: "Registro en el campo",
    marcetGameAction: "Momento de juego",
    marcetShirt: "Marcet • Camiseta 3",
    marcetDevelopment: "Experiencia de formación",
    marcetPositioning: "Posicionamiento en el campo",
    marcetTeam: "Registro del equipo",
    micKicker: "MIC Football 2026 — Cataluña",
    micTitle: "Competición internacional",
    micIntro: "Imágenes de la participación de Thiago con BCN Academy en la competición internacional celebrada en Cataluña.",
    micCarry: "Conducción de balón",
    micProtection: "Protección del balón",
    micPreparation: "Preparación para el partido",
    micReading: "Lectura de juego",
    micTactics: "Orientación táctica",
    liteKicker: "Lite Soccer — actuación en el campo",
    liteTitle: "Desarrollo competitivo",
    liteIntro: "Imágenes autorizadas de Thiago en partidos con Lite Soccer.",
    liteFinish: "Finalización con el pie izquierdo",
    liteAttack: "Acción ofensiva",
    litePositioning: "Posicionamiento en el campo",
    liteDuel: "Disputa de balón",
    liteTeam: "Registro del equipo Lite Soccer",
    liteAltFinish: "Thiago Cicala finalizando con el pie izquierdo en un partido con Lite Soccer",
    liteAltAttack: "Thiago Cicala avanzando con el balón en una acción ofensiva con Lite Soccer",
    liteAltPositioning: "Thiago Cicala posicionándose en el campo con el uniforme de Lite Soccer",
    liteAltDuel: "Thiago Cicala disputando el balón durante un partido de Lite Soccer",
    liteAltTeam: "Registro colectivo del equipo Lite Soccer en el campo",
    achievementsKicker: "06 — Logros",
    achievementsTitle: "Registro confirmado",
    championship: "Campeonato Municipal de Louveira",
    champion: "Campeón con Guarani",
    decisiveGoal: "Gol de la victoria en el último minuto de la final",
    contactKicker: "07 — Contacto institucional",
    contactTitle: "Contacto del responsable",
    contactText: "Los contactos, evaluaciones y oportunidades deportivas son administrados exclusivamente por el responsable legal del atleta.",
    backTop: "Volver arriba ↑"
  },
  en: {
    skip: "Skip to content",
    brandRole: "Athlete profile",
    menu: "Open menu",
    navProfile: "Profile",
    navVideos: "Videos",
    navJourney: "Journey",
    navContact: "Contact",
    heroEyebrow: "Brazilian athlete • U15",
    heroPosition: "Left-footed centre-back <i>•</i> Left-back",
    heroRoute: "Brazil <span>↗</span> Spain",
    watchHighlights: "Watch highlights",
    viewProfile: "View athlete profile",
    institutionalContact: "Institutional contact",
    downloadCv: "Download sports CV",
    photoFallback: "Football athlete",
    photoLabel: "Centre-back • Left-back",
    profileKicker: "01 — Athlete data",
    profileTitle: "Objective information",
    category: "Category",
    mainPosition: "Primary position",
    secondaryPosition: "Secondary position",
    centerBack: "Centre-back",
    leftBack: "Left-back",
    dominantFoot: "Dominant foot",
    leftFoot: "Left",
    nationality: "Nationality",
    brazilian: "Brazilian",
    base: "Base",
    baseValue: "São Paulo, Brazil",
    experience: "Experience",
    experienceValue: "Brazil and Spain",
    languages: "Languages",
    languagesValue: "Portuguese, English and Spanish",
    highlightsKicker: "02 — Highlights",
    highlightsTitle: "Videos for analysis",
    highlightsIntro: "Available footage for observing the athlete on the pitch.",
    mainVideo: "Main video",
    videoTwo: "Video 02",
    videoThree: "Video 03",
    highlightsName: "Highlights — Thiago Cicala",
    openYoutube: "Open on YouTube ↗",
    finalVideoLabel: "Final",
    finalVideoTitle: "Decisive final goal — Thiago Cicala",
    finalIframeTitle: "Thiago Cicala's decisive goal in the Louveira Municipal Championship final",
    semifinalVideoLabel: "Semi-final",
    semifinalVideoTitle: "Semi-final goal — Thiago Cicala",
    semifinalIframeTitle: "Thiago Cicala's goal in the Louveira Municipal Championship semi-final",
    semifinalKicker: "Guarani — Louveira Municipal Championship",
    semifinalTitle: "Direct contribution to the comeback",
    semifinalDescription: "Thiago provided the assist for the equaliser and scored the comeback goal, helping Guarani qualify for the final.",
    semifinalStatsLabel: "Semi-final indicators",
    semifinalAssist: "assist",
    semifinalGoal: "goal",
    semifinalQualification: "Qualification for the final",
    semifinalAltDuel: "Thiago Cicala challenging for the ball in the Louveira Municipal Championship semi-final",
    semifinalAltBall: "Thiago Cicala with the ball during the semi-final for Guarani",
    semifinalAltPortrait: "Portrait of Thiago Cicala on the pitch wearing the Guarani shirt",
    semifinalAltTeam: "Thiago Cicala with Guarani teammates after qualifying for the final",
    semifinalCaptionDuel: "Challenging for the ball in the semi-final",
    semifinalCaptionBall: "Thiago with the ball",
    semifinalCaptionPortrait: "Focused on the pitch",
    semifinalCaptionTeam: "After qualifying for the final",
    semifinalVideoActionsLabel: "Semi-final video",
    watchSemifinalGoal: "Watch the semi-final goal",
    openSemifinalYoutube: "Open on YouTube ↗",
    finalKicker: "Final — Louveira Municipal Championship",
    finalTitle: "Decisive goal in the final minute",
    finalDescription: "In the Louveira Municipal Championship final, Thiago scored the winning goal in the final minute to confirm Guarani's title.",
    finalStatsLabel: "Final highlights",
    finalWinningGoal: "Winning goal",
    finalLastMinute: "Final minute",
    finalChampion: "Title secured",
    finalCelebration: "Decisive goal celebration",
    finalPitch: "Focused in the final",
    finalShirt: "Guarani • Number 7",
    finalLineup: "Team before the final",
    finalTrophy: "After the title",
    finalTeammates: "Teammates and trophy",
    finalChampions: "Guarani champions",
    finalAltCelebration: "Thiago Cicala celebrating the decisive winning goal in the final minute of the final",
    finalAltPitch: "Thiago Cicala on the pitch during the final for Guarani",
    finalAltShirt: "Thiago Cicala on the pitch wearing Guarani's number 7 shirt",
    finalAltLineup: "Guarani team gathered on the pitch before the final",
    finalAltTrophy: "Thiago Cicala holding the trophy after winning the title with Guarani",
    finalAltTeammates: "Thiago Cicala with Guarani teammates and the championship trophy",
    finalAltChampions: "Guarani team gathered with the trophy after winning the championship",
    finalVideoActionsLabel: "Final video",
    watchFinalGoal: "Watch the final goal",
    openFinalYoutube: "Open on YouTube ↗",
    qualitiesKicker: "03 — Characteristics",
    qualitiesTitle: "On-pitch profile",
    technical: "Technical",
    technicalText: "Short passing, long passing, ball carrying and build-up from defence.",
    tactical: "Tactical",
    tacticalText: "Game reading, positioning, covering and support in build-up play.",
    physical: "Physical",
    physicalText: "Jumping, speed, presence in duels and recovery ability.",
    developing: "In development",
    developingText: "Finishing, attacking range and continued technical development.",
    preparationKicker: "Multidisciplinary preparation",
    preparationTitle: "Football-oriented physical development",
    preparationIntro: "A complementary structure combining athletics and individualised training to broaden Thiago's physical and sporting development.",
    athleticsTitle: "Applied athletics",
    athleticsText: "For the past four months, Thiago has undertaken complementary athletics work at CBAt under coach Marcelo, a professional who has won gold medals in athletics competitions.",
    footballPersonalTitle: "Individualised training",
    footballPersonalText: "Personalised work with coach Paulo Capucho, focused on the specific physical and sporting demands of football.",
    appliedExperienceTitle: "High-performance experience",
    appliedExperienceText: "Thiago also works with coach Robinho, a former athlete developed in Santos' youth system who reached Bragantino's first team at a very young age, played in Belgium and now works in athlete development.",
    journeyKicker: "04 — Journey",
    journeyTitle: "Football development",
    journeyIntro: "Training, development, tournament and observation experiences in Brazil and Spain.",
    timelineStart: "Start of development",
    timelineStartText: "First years of training and building core skills.",
    timelineFirstTeam: "First team",
    timelineFirstTeamText: "Entry into organised football in the state of São Paulo.",
    timelineMethod: "Development experience",
    timelineMethodText: "Contact with a training methodology linked to the Barcelona academy.",
    timelineMicText: "Participation in an international competition in Catalonia with BCN Academy.",
    timelineMislataText: "Training and observation period in Valencia, Spain.",
    current: "Current",
    timelineBrazil: "Development in Brazil",
    timelineBrazilText: "Technical, physical and competitive development in Brazil.",
    next: "Next",
    timelineGoal: "Professional objective",
    timelineGoalText: "Continue developing in a competitive environment while combining football and education.",
    internationalKicker: "05 — International experience",
    internationalTitle: "Experiences in Spain",
    internationalText: "Development experience in Barcelona, competition in Catalonia and a training and observation period in Valencia.",
    catalonia: "Catalonia",
    valencia: "Valencia",
    marcetKicker: "Marcet — on-pitch record",
    marcetTitle: "Development experience",
    marcetIntro: "Authorised images of Thiago taking part in sporting activities with Marcet.",
    marcetAction: "Challenging for the ball",
    marcetMatch: "On-pitch record",
    marcetGameAction: "Match action",
    marcetShirt: "Marcet • Number 3",
    marcetDevelopment: "Development experience",
    marcetPositioning: "On-pitch positioning",
    marcetTeam: "Team record",
    micKicker: "MIC Football 2026 — Catalonia",
    micTitle: "International competition",
    micIntro: "Images of Thiago representing BCN Academy in the international competition held in Catalonia.",
    micCarry: "Ball carrying",
    micProtection: "Ball protection",
    micPreparation: "Match preparation",
    micReading: "Game reading",
    micTactics: "Tactical guidance",
    liteKicker: "Lite Soccer — on-pitch action",
    liteTitle: "Competitive development",
    liteIntro: "Authorised images of Thiago playing matches with Lite Soccer.",
    liteFinish: "Left-footed finish",
    liteAttack: "Attacking action",
    litePositioning: "On-pitch positioning",
    liteDuel: "Challenging for the ball",
    liteTeam: "Lite Soccer team record",
    liteAltFinish: "Thiago Cicala finishing with his left foot in a match for Lite Soccer",
    liteAltAttack: "Thiago Cicala advancing with the ball in an attacking action for Lite Soccer",
    liteAltPositioning: "Thiago Cicala positioning himself on the pitch in the Lite Soccer kit",
    liteAltDuel: "Thiago Cicala challenging for the ball during a Lite Soccer match",
    liteAltTeam: "Lite Soccer team record on the pitch",
    achievementsKicker: "06 — Achievements",
    achievementsTitle: "Confirmed record",
    championship: "Louveira Municipal Championship",
    champion: "Champion with Guarani",
    decisiveGoal: "Winning goal in the final minute of the final",
    contactKicker: "07 — Institutional contact",
    contactTitle: "Guardian contact",
    contactText: "Contacts, assessments and sporting opportunities are managed exclusively by the athlete's legal guardian.",
    backTop: "Back to top ↑"
  }
};

const menuButton = document.querySelector(".menu-toggle");
const menu = document.querySelector("#menu-principal");
const languageButtons = document.querySelectorAll("[data-lang]");
const photo = document.querySelector(".hero-photo");

function setMenu(open) {
  menuButton.setAttribute("aria-expanded", String(open));
  menu.classList.toggle("is-open", open);
  document.body.classList.toggle("menu-open", open);
}

menuButton.addEventListener("click", () => setMenu(menuButton.getAttribute("aria-expanded") !== "true"));
menu.querySelectorAll("a").forEach((link) => link.addEventListener("click", () => setMenu(false)));
window.addEventListener("resize", () => {
  if (window.innerWidth > 720) setMenu(false);
});

function setLanguage(lang) {
  const dictionary = translations[lang] || translations.pt;
  document.documentElement.lang = lang === "pt" ? "pt-BR" : lang;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (lang === "pt") {
      if (!element.dataset.original) element.dataset.original = element.innerHTML;
      element.innerHTML = element.dataset.original;
      return;
    }
    if (!element.dataset.original) element.dataset.original = element.innerHTML;
    if (dictionary[key]) element.innerHTML = dictionary[key];
  });

  document.querySelectorAll("[data-i18n-alt]").forEach((element) => {
    const key = element.dataset.i18nAlt;
    if (!element.dataset.originalAlt) element.dataset.originalAlt = element.alt;
    element.alt = lang === "pt" ? element.dataset.originalAlt : (dictionary[key] || element.dataset.originalAlt);
  });

  document.querySelectorAll("[data-i18n-aria]").forEach((element) => {
    const key = element.dataset.i18nAria;
    if (!element.dataset.originalAria) element.dataset.originalAria = element.getAttribute("aria-label") || "";
    element.setAttribute("aria-label", lang === "pt" ? element.dataset.originalAria : (dictionary[key] || element.dataset.originalAria));
  });

  document.querySelectorAll("[data-i18n-title]").forEach((element) => {
    const key = element.dataset.i18nTitle;
    if (!element.dataset.originalTitle) element.dataset.originalTitle = element.title;
    element.title = lang === "pt" ? element.dataset.originalTitle : (dictionary[key] || element.dataset.originalTitle);
  });

  languageButtons.forEach((button) => button.setAttribute("aria-pressed", String(button.dataset.lang === lang)));
  localStorage.setItem("thiago-site-language", lang);

  const titles = {
    pt: "Thiago Cicala | Zagueiro canhoto Sub-15",
    es: "Thiago Cicala | Defensa central zurdo Sub-15",
    en: "Thiago Cicala | Left-footed U15 centre-back"
  };
  document.title = titles[lang] || titles.pt;
}

languageButtons.forEach((button) => button.addEventListener("click", () => {
  setLanguage(button.dataset.lang);
  setMenu(false);
}));

if (photo) {
  photo.addEventListener("error", () => photo.classList.add("is-unavailable"));
  if (photo.complete && photo.naturalWidth === 0) photo.classList.add("is-unavailable");
}

setLanguage(localStorage.getItem("thiago-site-language") || "pt");
